### ISSUE TITLE
[BUG] dont set the start point right (4k screen)

### ISSUE THREAD

**Issue by R0TEAM** [voodoofrog/foundryvtt-celebrate#11]
After use it one time flawless (here thanks for the nice idea) ...
The next Time it practicaly work ... but i as the GM cant see it most times ...
The player see it as before ... no problems ...
But on my monitor, it looks the corners are misscalculated ...
Its look it is way to down und way to much right .... barely i see the left celebration happen on medium and on full i see the left and a bit of the right .. on low i see nothing ...
Have not changed anything to the system ..... strange

**Comment by voodoofrog** [comment]
Hm, this'll be a hard one for me to diagnose as I don't have a 4k screen myself. Curious that it worked correctly to begin with though. Did you change your modules between that first time and the time it stopped working?

**Comment by R0TEAM** [comment]
have found with the 1.3.0 it works flawless ....
maybe the reason is the "old" 2.x DnD5e version i use - have not upgraded to the new 3.x .... (but it is planed)

**Comment by voodoofrog** [comment]
Glad you found a resolution. :)
