### ISSUE TITLE
[Feature Request] MATT Integration

### ISSUE THREAD

**Issue by Crowguard** [voodoofrog/foundryvtt-celebrate#8]
Crossposting from https://github.com/ironmonk88/monks-active-tiles/issues/727

With Confetti no longer being maintained, Celebrate has basically replaced it. Could Celebrate be integrated into MATT at some point in the future?

**Comment by voodoofrog** [comment]
Celebrate has an API. It's up to the devs of MATT if they wish to integrate it into their module. That said - since you can fire confetti programmatically, you could just have MATT trigger a macro if that's what you are looking for? There are example macros in a compendium.
